version: '3.9'
services: 
    mongo_db:
        container_name: mongo-db
        image: mongo:latest
        env_file:
          - ./config/mongodb.env
        ports:
          - 27017:27017
        volumes:
          - mongo_db_data:/data/db
        networks: 
          - mongo-compose-network
    mongo_express:
        container_name: mongo-express
        image: mongo-express:latest
        depends_on:
          - mongo_db
        env_file:
          - ./config/mongoexpress.env
        ports:
          - 8081:8081
        networks: 
          - mongo-compose-network
        deploy:
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 10
            window: 120s
volumes:
  mongo_db_data:
networks:
  mongo-compose-network:
    driver: bridge